### ISSUE TITLE
2024-01-30 Fix custom tooltip for main signals

### ISSUE THREAD

**Issue by khhelland** [Railcomplete-AS/RailCOMPLETE-DNA-NO-BN#209]
Custom tooltip: Distance feiler på hovedsignalobjekter.

**Comment by khhelland** [comment]
Also look for other bugs in custom tooltips.

**Comment by svknoe** [comment]
da98e8c0973fbaba5b95fbd01b83eb11ebb59f53

Alignment Info had stopped working, I fixed it by replacing isNaN-checks with nil-checks.

@clfey This happened because I changed the meaning of 'NaN'. I should have been more thorough in looking for problems caused by this.

Previously NaN implicitly meant "there is either a mathematical error or missing data". I think that this throws away valuable information. In particular, real errors are sometimes interpreted as missing data and masked by being converted to 0. Therefore these two cases should be distinguished.

The problem is that some existing Lua functions expect NaN and are unprepared for nil.

Our options going forwards:
- A) I go through all our DNA functions, replacing isNaN-checks with nil-checks.
    - This is my preferred option.
- B) I revert the change in meaning, keeping it only in C#, and throwing away the extra information in Lua.

**Comment by clfey** [comment]
Please evaluate - there is a DNA function called RC__isNaN() which simply returns `x ~= x` - are calls to RC__isNaN affected?

**Comment by svknoe** [comment]
Yes. `x ~= x` evaluates as `true` for `NaN` and `false` for `nil`.

**Comment by svknoe** [comment]
1e44854434a96edebe44951673df2b8ad78b767d
