### ISSUE TITLE
2024-01-30 check 3D offset.Z for etcs

### ISSUE THREAD

**Issue by khhelland** [Railcomplete-AS/RailCOMPLETE-DNA-NO-BN#212]
Sjekk i E18 (etc, trolig en annen) at offset.Z i 3D er riktig for alle ETCS-skilt.

**Comment by svknoe** [comment]
Taken from BaneNOR's "ERTMS Programme - Design requirements - Signs and boards":

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/33001939/2c28981b-2227-4a01-9d16-e7a05371d103)

There are three types of ERTMS signs that need different types for Offset.Z formulas:
- ID signs (JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt)
  - Fixed height, typically 2.5m.
- Stop signs (JBTSA_ERT ERTMS-signal, possibly only certain variants)
  - Placed on top of ID sign, with a 1cm gap. Height becomes `height of ID sign/2 + 1cm + height of stop sign / 2`. Unclear what to do if ID sign is missing. 
- Other signs (JBTSA_MSS ERTMS Signalskilt ?).
  - A collection of sign, all placed below the ID sign, in accordance with some more complicated logic.

TODO:

- [x] Make ID sign Offset.Z formulas.
- [x] Make stop sign Offset.Z formulas.
- [x] Make other signs Offset.Z formulas. Maybe this is too hard.

**Comment by svknoe** [comment]
d43ee5f306361e3f2a8a35bd276751508b22ce47

Handled formulas for ID signs.

**Comment by svknoe** [comment]
**Stop sign Z offsets**
Currently, our ETCS stop signs are modelled by `JBTSA_ERT ERTMS-signal`. It has a few variants, each possibly including a stop sign and possibly a dwarf signal, but always at least one of them. The stop sign (should) correspond(s) to `Geometry3D_0`, so that's where we're going to add our Z offset formula.

The stop sign usually has an attached ID sign. If not, use can use a default value. If the ID sign is present, we make the Z offset of the stop sign depend on the Z offset of the ID sign, as described in an above post. To find the relevant ID sign, we have to search through the attachments of the ID sign, looking for one of the four variants that are ID signs for stop signs. We can do that in a manner similar to the following:

``` Lua
for i = 0, AttachedElements.Count - 1 do
	if AttachedElements[i].RcType == rctype_SignEtcsId then
		if (AttachedElements[i].Variant == "Signal E101-A ID-skilt, Indre, 400x325, hvit" 
		or AttachedElements[i].Variant == "Signal E101-B ID-skilt, Innkjør, 400x325, gul" 
		or AttachedElements[i].Variant == "Signal E101-C ID-skilt, Utkjør, Ø400, gul" 
		or AttachedElements[i].Variant == "Signal E101-D ID-skilt, Blokk, Ø400, hvit") then
			return -- Do work here
		end
	end
end
```

There's only supposed to be max 1, so we can pick the first one, if any. When we find it we have to figure out its height, typically either 325mm or 400mm, see variant name. Then we have to figure out the height of the stop sign, before finally setting its Z offset to `height of ID sign/2 + 1cm + height of stop sign / 2`, rounded up to the nearest cm.

**Comment by svknoe** [comment]
0301118723da54bf97fab1ee9bb5d03e34c80c57

I've finished the Z offset formula for stop signs, see results below. What remains of this issue is for me to figure out what I want to do with the more complicated 'other signs' case. I'll probably write a partial formula for simple cases and leave complicated cases to the user.

Success:
![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/33001939/0952c222-ae3c-496d-b0b7-ab31cf7d78a1)

Temporary failure:
![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/33001939/3ff7b1f0-b811-40b6-9897-5c34c482a66e)

It seems that the 3D for stop sign + dwarf is a single 3D model. Since we have decided to split these into two separate entities I think it's better for me to leave it like this now than to compensate for the error in my formula.

**Comment by svknoe** [comment]
## Plan for 'other signs' Offset.Z formulas
The behaviour I want to change is governed by the existing Lua formula `NOBN_bnp_getBoardOffset3DZ()`. My goal for this issue is to edit that formula to handle the middle case in the above picture (https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/issues/212#issuecomment-1981031644). Interactions between different types of 'other signs' is too hard.

A complication is that `NOBN_bnp_getBoardOffset3DZ()` already contains some logic. Maybe it pertains to interactions between signs. Try to preserve what's there, if it's useful.

## Workflow for 'other signs' Offset.Z formulas
- Make a formula for `JBTSA_MSS ERTMS Signalskilt` on `Geometry3D_0.Offset.Z`:
  - Check if the pole has a stop sign.
    - If so, check if the stop sign has an ID sign,
      - If so, place the sign 1cm below the ID sign,
      - else pretend that an ID sign exists and is 325mm tall. Place the sign below it.
    - else try to interpret old formula for default behaviour.
- Figure out which ID sign variant belongs to each 'other sign' variant. For each 'other sign' variant:
  - Go to the "Design requirements - Signs and boards" document, scroll through it, and find the sign that corresponds to the variant.
  - Go to the page below it - it shows the corresponding ID sign.
  - Go through the variants of `JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt` and figure out which variant corresponds to the ID sign from the above step.
- Edit the `Geometry3D_0.Offset.Z` formula for `JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt`:
  - For each variant that corresponds to an 'other sign' variant, check if the pole has a sign of that variant.
    - If so, place the ID sign 1cm below it,
    - else the ID sign shouldn't really be there - give it z offset 0.

**Comment by svknoe** [comment]
a7287e35595ab04c3379773934c816dbe621ba4c

Updated Z offset formula for `JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt` to account for cases where they are attached to 'other signs'.

**Comment by svknoe** [comment]
7ba028d65bd48283f785dd9df317674abf64abc8

Updated Z offset formula for 'other signs'. This concludes the above todos.
